
TRUNCATE TABLE USER_CATEGORY CASCADE;
TRUNCATE TABLE OSUSER CASCADE;
TRUNCATE TABLE PROJECT CASCADE;
TRUNCATE TABLE USER_PROJECT CASCADE;
TRUNCATE TABLE COMPONENT CASCADE;
TRUNCATE TABLE COMPONENT_VERSION CASCADE;
TRUNCATE TABLE WORKFLOW_INSTANCE CASCADE;
TRUNCATE TABLE WORKFLOW_STATUS CASCADE;
TRUNCATE TABLE COMPONENT_REFERENCE CASCADE;
TRUNCATE TABLE TAG CASCADE;
TRUNCATE TABLE COMPONENT_TAG CASCADE;
TRUNCATE TABLE USER_COMPONENT CASCADE;
TRUNCATE TABLE COMMENT CASCADE;
TRUNCATE TABLE ESTIMATED_TIME CASCADE;
